apiVersion: sa.upbound.io/v1
kind: XUpboundRepoSet
metadata:
  name: example
spec:
  parameters:
    organization: upboundcare
    permissions:
      teams:
        solutions-non-prod-ci-team:
          permission: write
    settings:
      public: true
      publish: true
    repositories:
      configuration-aws-network: {}
      configuration-aws-network_xnetwork:
        public: false
        publish: false
    tokenSecretRef:
      name: solutions-non-prod-bootstrap-token
      namespace: default
      key: token
